# CARDIOVASCULAR DISEASE PREDICTION

In [193]:
import pandas as pd;
import numpy as np;
from sklearn.preprocessing import StandardScaler;
from sklearn.model_selection import train_test_split;
from sklearn.linear_model import LogisticRegression;
from sklearn.metrics import accuracy_score;

## Data Colllection and Preprocessing

In [194]:
dataframe=pd.read_csv('./cardio_data_processed.csv')

In [195]:
dataframe.head()

,id,age,gender,height,weight,ap_hi,ap_lo,cholesterol,gluc,smoke,alco,active,cardio,age_years,bmi,bp_category,bp_category_encoded
0,0,18393,2,168,62.0,110,80,1,1,0,0,1,0,50,21.967120,Hypertension Stage 1,Hypertension Stage 1
1,1,20228,1,156,85.0,140,90,3,1,0,0,1,1,55,34.927679,Hypertension Stage 2,Hypertension Stage 2
2,2,18857,1,165,64.0,130,70,3,1,0,0,0,1,51,23.507805,Hypertension Stage 1,Hypertension Stage 1
3,3,17623,2,169,82.0,150,100,1,1,0,0,1,1,48,28.710479,Hypertension Stage 2,Hypertension Stage 2
4,4,17474,1,156,56.0,100,60,1,1,0,0,0,0,47,23.011177,Normal,Normal

In [196]:
changes={
    'Normal':0,
    'Hypertension Stage 1':1,
    'Hypertension Stage 2':2,
    'Elevated':3,
    'Hypertensive Crisis':4
}
dataframe['bp_category']=dataframe['bp_category'].map(changes)
dataframe['bp_category_encoded']=dataframe['bp_category_encoded'].map(changes)

In [197]:
dataframe.head()

,id,age,gender,height,weight,ap_hi,ap_lo,cholesterol,gluc,smoke,alco,active,cardio,age_years,bmi,bp_category,bp_category_encoded
0,0,18393,2,168,62.0,110,80,1,1,0,0,1,0,50,21.967120,1,1
1,1,20228,1,156,85.0,140,90,3,1,0,0,1,1,55,34.927679,2,2
2,2,18857,1,165,64.0,130,70,3,1,0,0,0,1,51,23.507805,1,1
3,3,17623,2,169,82.0,150,100,1,1,0,0,1,1,48,28.710479,2,2
4,4,17474,1,156,56.0,100,60,1,1,0,0,0,0,47,23.011177,0,0

In [198]:
dataframe.tail()

,id,age,gender,height,weight,ap_hi,ap_lo,cholesterol,gluc,smoke,alco,active,cardio,age_years,bmi,bp_category,bp_category_encoded
68200,99993,19240,2,168,76.0,120,80,1,1,1,0,1,0,52,26.927438,1,1
68201,99995,22601,1,158,126.0,140,90,2,2,0,0,1,1,61,50.472681,2,2
68202,99996,19066,2,183,105.0,180,90,3,1,0,1,0,1,52,31.353579,2,2
68203,99998,22431,1,163,72.0,135,80,1,2,0,0,0,1,61,27.099251,1,1
68204,99999,20540,1,170,72.0,120,80,2,1,0,0,1,0,56,24.913495,1,1

In [199]:
dataframe.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 68205 entries, 0 to 68204
Data columns (total 17 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   id                   68205 non-null  int64
 1   age                  68205 non-null  int64
 2   gender               68205 non-null  int64
 3   height               68205 non-null  int64
 4   weight               68205 non-null  float64
 5   ap_hi                68205 non-null  int64
 6   ap_lo                68205 non-null  int64
 7   cholesterol          68205 non-null  int64
 8   gluc                 68205 non-null  int64
 9   smoke                68205 non-null  int64
 10  alco                 68205 non-null  int64
 11  active               68205 non-null  int64
 12  cardio               68205 non-null  int64
 13  age_years            68205 non-null  int64
 14  bmi                  68205 non-null  float64
 15  bp_category          68205 non-null  int64
 16  bp_category_encoded  68205 non-null  int64
dtypes: float64(2), int64(15)
memory usage: 8.8 MB

In [200]:
dataframe.describe()

,id,age,gender,height,weight,ap_hi,ap_lo,cholesterol,gluc,smoke,alco,active,cardio,age_years,bmi,bp_category,bp_category_encoded
count,68205.000000,68205.000000,68205.000000,68205.000000,68205.000000,68205.000000,68205.000000,68205.000000,68205.000000,68205.000000,68205.000000,68205.000000,68205.000000,68205.000000,68205.000000,68205.000000,68205.000000
mean,49972.410498,19462.667737,1.348625,164.372861,74.100688,126.434924,81.263925,1.363243,1.225174,0.087662,0.053134,0.803548,0.493688,52.823635,27.510513,1.186526,1.186526
std,28852.138290,2468.381854,0.476539,8.176756,14.288862,15.961685,9.143985,0.678080,0.571288,0.282805,0.224302,0.397317,0.499964,6.769909,6.026497,0.720286,0.720286
min,0.000000,10798.000000,1.000000,55.000000,11.000000,90.000000,60.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,29.000000,3.471784,0.000000,0.000000
25%,24991.000000,17656.000000,1.000000,159.000000,65.000000,120.000000,80.000000,1.000000,1.000000,0.000000,0.000000,1.000000,0.000000,48.000000,23.875115,1.000000,1.000000
50%,50008.000000,19700.000000,1.000000,165.000000,72.000000,120.000000,80.000000,1.000000,1.000000,0.000000,0.000000,1.000000,0.000000,53.000000,26.346494,1.000000,1.000000
75%,74878.000000,21323.000000,2.000000,170.000000,82.000000,140.000000,90.000000,1.000000,1.000000,0.000000,0.000000,1.000000,1.000000,58.000000,30.116213,2.000000,2.000000
max,99999.000000,23713.000000,2.000000,250.000000,200.000000,180.000000,120.000000,3.000000,3.000000,1.000000,1.000000,1.000000,1.000000,64.000000,298.666667,3.000000,3.000000

In [201]:
dataframe.shape

(68205, 17)

In [202]:
dataframe.isnull().sum()

id                     0
age                    0
gender                 0
height                 0
weight                 0
ap_hi                  0
ap_lo                  0
cholesterol            0
gluc                   0
smoke                  0
alco                   0
active                 0
cardio                 0
age_years              0
bmi                    0
bp_category            0
bp_category_encoded    0
dtype: int64

In [203]:
dataframe["gender"] = dataframe["gender"].astype(int)  # Already numerical
dataframe["cholesterol"] = dataframe["cholesterol"].astype(int)
dataframe["gluc"] = dataframe["gluc"].astype(int)
dataframe["smoke"] = dataframe["smoke"].astype(int)
dataframe["alco"] = dataframe["alco"].astype(int)
dataframe["active"] = dataframe["active"].astype(int)

In [204]:
mapped={
    1:0,
    2:1
}

dataframe['gender']=dataframe['gender'].map(mapped)

In [205]:
dataframe["cardio"].value_counts()

cardio
0    34533
1    33672
Name: count, dtype: int64

In [206]:
dataframe.groupby('cardio').mean()

,id,age,gender,height,weight,ap_hi,ap_lo,cholesterol,gluc,smoke,alco,active,age_years,bmi,bp_category,bp_category_encoded
cardio,,,,,,,,,,,,,,,,
0,49863.923870,18880.051400,0.345756,164.463904,71.591605,119.597631,78.167811,1.215417,1.175021,0.092289,0.055136,0.818435,51.226769,26.541240,1.001332,1.001332
1,50083.671151,20060.181694,0.351568,164.279490,76.673929,133.447048,84.439208,1.514849,1.276610,0.082918,0.051081,0.788281,54.461333,28.504571,1.376455,1.376455

## Splitting the Features and Labels

In [207]:
X=dataframe.drop('cardio',axis=1)
Y=dataframe['cardio']

In [208]:
print(X.shape)

(68205, 16)

In [209]:
print(Y.shape)

(68205,)

## STANDARDIZE THE DATA

In [210]:
scaler=StandardScaler()

In [211]:
X=scaler.fit_transform(X)

## SPLITTING INTO TRAINED AND TESTED DATA

In [212]:
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2,stratify=Y,random_state=2)

In [213]:
print(X.shape,X_train.shape,X_test.shape)

(68205, 16) (54564, 16) (13641, 16)

In [214]:
print(Y.shape,Y_train.shape,Y_test.shape)

(68205,) (54564,) (13641,)

## Building the Model

In [215]:
regression=LogisticRegression()

In [216]:
regression.fit(X_train,Y_train)

LogisticRegression()

## EVALUATE THE MODEL

### ACCURACY SCORE FOR TRAINED DATA

In [217]:
X_train_predict=regression.predict(X_train)

In [218]:
prediction1=accuracy_score(X_train_predict,Y_train)

In [219]:
print("Accuracy score for trained data : ",prediction1)

Accuracy score for trained data :  0.7266512719008871

### Accuracy score for Tested Data

In [220]:
X_test_predict=regression.predict(X_test)

In [221]:
prediction2=accuracy_score(X_test_predict,Y_test)

In [222]:
print("Accuracy score for Tested data : ",prediction2)

Accuracy score for Tested data :  0.7289788138699509

## BULIDING Predictive  System

In [223]:
input_data =(0,18393,2,168,62.0,110,80,1,1,0,0,1,50,21.9671201814059,1,1)

input_data=(1,20228,1,156,85.0,140,90,3,1,0,0,1,55,34.927679158448385,2,2
)

arr=np.asarray(input_data)

In [224]:
arr_reshaped=arr.reshape(1,-1)

### STANDARDIZE THE INPUT DATA

In [225]:
std_data=scaler.transform(arr_reshaped)

c:\Users\Kanishka\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(

### Prediction for input data

In [226]:
predict=regression.predict(std_data)

In [227]:
print("Prediction for input data ",predict[0])

Prediction for input data  1

In [228]:
if(predict[0]==0):
    print("The person does not have any cardiovascular disease .")
else:
    print("The person has cardiovascular disease .")

The person has cardiovascular disease .